### ISSUE TITLE
h_32 feladat ellenőrzése

### ISSUE THREAD

**Issue by budaibarna** [PE-MK-JAKI-H/MHEK#10]
Tisztelt Tanár Úr!

Kérem ellenőrizze a kész feladatomat! A hőcserélő jellemzése azért lett csak pár sor, mert hosszabb esetben oldaltörést végzett. Ha úgy is jó, természetesen leírom a részletesebb módon is. Végül a köpenyoldalon egyszeres, csőoldalon kétszeres átfutású megoldást választottam azok közül, amit Ön javasolt. A másik hallgatónak elküldtem az instrukciót, remélem ő is megcsinálja a saját verzióját (köpenyoldalon és csőoldalon is kétszeres átfutású).

Üdvözlettel,
Budai Barna

**Comment by Szalay** [comment]
Megnéztem a beadandót, és van két javítandó probléma:
1) A T(A) diagramhoz írtam, hogy kell egy számítás, hogy ésszerű értékek legyenek ábrázolva. Ez hiányzik.
2) Az úszófej mögött rajt hagytad a merev csőköteges hőcserélő jobboldali fejét.

Ezeket javítani kellene. A végső határidő jövő hétfő.

**Comment by budaibarna** [comment]
Tisztelt Tanár Úr!

1. Legyenek számértékek is ábrázolva, vagy konkrétan az LMTD legyen
levezetve?

2. Ezt most őszintén nem látom az enyémen. Esetleg valami képernyő képpel
meg tudná mutatni mire gondol?

Üdv,
Budai Barna

Szalay <notifications@github.com> (időpont: 2020. máj. 26., K, 23:16) ezt
írta:

**Comment by Szalay** [comment]
Az ábránál a kék kettes folyadékkal kitöltve ott maradt a jobboldali csőoldali fej:
![image](https://user-images.githubusercontent.com/8204804/82952423-383c8080-9fa9-11ea-8ad2-3dbadaf278bb.png)

**Comment by Szalay** [comment]
A számításos részen az érdekel, hogy honnan jöttek ezek a hőmérséklet értékek:
![image](https://user-images.githubusercontent.com/8204804/82952493-57d3a900-9fa9-11ea-97db-f8fc210933dc.png)

**Comment by budaibarna** [comment]
Azok az értékek a mintafeladatból maradtak benne, de a diagrammon nincsenek
ábrázolva. Mivel elméleti a kérdés csak általános jelölések vannak. Ugyan
így láttam egy másik hőcserélős beadandóban is.
A kitöltés részéhez egy kis segítséget kérnék, mert amikor próbáltam
megváltoztatni, nem sikerült túl szépre, ezért hagytam inkább ugyan olyan
színre.

Szalay <notifications@github.com> (időpont: 2020. máj. 26., K, 23:34) ezt
írta:

**Comment by budaibarna** [comment]
Megnyitottam és ellenőriztem. Ha megengedi kicsit vitába szállnék. Azok az
értékek az Ön álltal kidolgozott egyik feladat értékei, ami alapján a hcs
T-A függvényét csináltam. De ez jelen esetben teljesen lényegtelen
(szerintem), mert úgysem szerepelnek az értékek a diagrammon.

Barna Budai <budaibarnamark@gmail.com> ezt írta (időpont: 2020. máj. 26.,
K, 23:39):

**Comment by budaibarna** [comment]
Illetve megcsináltam a szín módosítását az úszófejnél, azt a kérdésemet
visszavonnám, előbb kérdeztem, mint gondolkodtam volna, elnézést. De a
függvényes témában kíváncsi vagyok a véleményére!

Barna Budai <budaibarnamark@gmail.com> ezt írta (időpont: 2020. máj. 27.,
Sze, 0:01):

**Comment by Szalay** [comment]
Nem csak színt kell módosítani, hanem merev csőköteg talplemeze sem kell. És a múltkor hibásan írtam úszófejet, a csövek ívelt részeire gondoltam.

A számítás pedig azért érdekes, mert ha megváltoztatod az átfutások számát, akkor egy eltérő vegyesáramú hőcserélőt kapsz, am miatt eltérőek lesznek hőmérséklet értékek, lehet, hogy helyet cserél a \DeltaT_N és a \DeltaT_K, más lesz íve a hőmérséklet-hely függvényeknek. Az igaz, hogy többé-kevésbé paraméterezhetőre írtam meg a 7/2-es ábráját, de egyrészt az eredeti feladattól eltérő értékekre soha nem teszteltem, másrészt pedig én írtam meg, te körül-belül 25 sort módosítottál, és teljes vízgőz T-s és p-v diagramokkal, kapcsolási vázlatokkal, többrétegű falak hőmérsékleteloszlásaival és elméleti levezetésekkel van versenyben a beadandód, amikor értékelem. Azaz egyrészt l kell ellenőrizni, hogy jók-e az értékek, amik kikerülnek, másrészt pedig mennyiségileg is fel kell mutatni valamit.

**Comment by budaibarna** [comment]
Tisztelt Tanár Úr!

A kért javításokat az Ön javaslatára, a szerdai nap végéig a számítással együtt feltöltöm!

**Comment by budaibarna** [comment]
Tisztelt Tanár Úr!

Végeztem a javításokkal, kérem nézze meg őket!

**Comment by Szalay** [comment]
Átnéztem és pontoztam, az eredményt megtalálod a Google-táblázatban, illetve látod a Neptunban is.
