### ISSUE TITLE
feltöltött feladat ellenőrzése

### ISSUE THREAD

**Issue by zsofibalogh** [PE-MK-JAKI-H/MHEK#12]
Jó napot Tanár Úr!
Feltöltöttem a 8-as és a 10-es feladatomat az MHEK-ból. Legyen szíves leellenőrizni és lepontozni. A harmadik feladatomat majd később töltöm fel.

**Comment by zsofibalogh** [comment]
Tisztelt Tanár Úr!
A harmadik feladatomat (MHEK-13-as) is feltöltöttem.

**Comment by Szalay** [comment]
Átnéztem és pontoztam a jelenlegi állapot alapján, az eredményt megtalálod a Google-táblázatban.

Ha szeretnéd a négyeshez hiányzó 0,75 pontot megszerezni, akkor a feladatleírásokban a $T-s$ és a $p-v$ legyen sorközi egyenlet, és differenciálokban a d ne sima d legyen, hanem \dif.

**Comment by zsofibalogh** [comment]
Tisztelt Tanár Úr!
Ki is javítottam, remélem mindenhol sikerült átírni.

**Comment by Szalay** [comment]
Nem sikerült mindenhol kijavítani, de kicsit jobb lett. A pontozást frissítettem.
