### ISSUE TITLE
MHEK 4/21

### ISSUE THREAD

**Issue by GroberAdel** [PE-MK-JAKI-H/MHEK#2]
Kedves Tanár Úr!
Azt szeretném kérdezni, hogy az osztásnál miért jelez pirosan a \dfrac ? Az egyenletek egyébként így jók lesznek? 

[hrcjno_4_21.zip](https://github.com/PE-MK-JAKI-H/MHEK/files/4470747/hrcjno_4_21.zip)

**Comment by Szalay** [comment]
A GitHub Desktopban csinálj egy commitota saját ágadon és egy push origint. Többek között arra való a GitHub, hogy ne kelljen kézzel, egyesével fájlokat küldözgetni egymásnak. Ha megvolt a push origin, akkor megjegyzést fogok tudni írni soronként a megoldásodhoz.

**Comment by Szalay** [comment]
Közben ránéztem azért a megoldásra is, és amit eddig megcsináltál az alapvetően rendben van, csak rossz helyen van és vannak formázási hibák. 
1) Az MHEK.textben csak az \input{hrcjno_421.tex} legyen, és minden más kerüljön a hrcjno_421.tex-be.
2) Az egyenletek ne center, hanem equation környezetbe kerüljenek, például az első: 

\begin{equation}
	w = q_{BE} - q_{EL}
\end{equation}

Az equationben nem kellenek a $ jelek sem, és számozott lesz az egyenlet. A Moodle-ben találsz példákat.

3) A \dfrac-nál van egy fölösleges szóköz az első és a második bemenetet közrefogó kapcsoszárójelek között.

**Comment by GroberAdel** [comment]
Tisztelt Tanár Úr! Elvégeztem a módosításokat, feltöltöttem az ágamra a fájlokat, és elkezdtem a rajzokat is. Azt szeretném kérdezni, hogy eddig jó-e, illetve a T-s diagramnál hogyan tudnám rátenni azt a vonalat, ami az 1-es és 2-es pontnál eltávolodik az eredeti görbétől. Vagy itt is kérjek le adatot a wolframcloud-ból? Csak ugye nincs konkrét adatom, mert nem számolás, hanem sima elméleti ábra.  Az alapfüggvény megvan a wolframcloudból, viszont nem tudom, hogy a körfolyamat ábráját hogyan "illesszem rá", mert erre előre megírt függvényt nem találtam. Látom az p=50 barhoz tartozó izobar függvényt a wolfram note vége felé, viszont ez nem az a vonal, ami nekem kellene, mert ez nem távolodik el az alap függvénytől.

**Comment by Szalay** [comment]
A következőket kell javítani:
1) A saját fájljaid egy neptun-kód nevű mappába kerüljenek.
2) A táblázatod első oszlopa hiányzik.
3) A kidolgozás ne felsorolás, hanem folyó szöveg jellegű legyen.
4) Az állapotváltozásokhoz kapcsolódó egyenletekhez kellene némi magyarázat.
5) A kazánnyomás, a lecsapató/kondenzátor nyomás és a túlhevítési hőmérséklet jelenjen meg, mint a körfolyamatot meghatározó három jellemző. Ez a szövegre és az ábrákra is vonatkozik.
6) A kapcsolási vázlat túl nagy, fele ekkor elég lenne. A szivattyú ás a generátor jelölését pontosítani kellene, és a szövegben megmagyarázni, hogy melyik betűjel mit jelöl.
7) A T-s diagramhoz kelleni fog az adat (ez a két izobár vonalat és a pontok helyeit jelenti), és a 6-1 szakaszt és a környezetét kinagyítva kellene ábrázolni. A körfolyamat a kiterjedési oldalon maradhat visszafordítható, de ezt is meg kell említeni a szövegben.
8) Területek megjelölését is kéri a feladat szövege.
9) A szivattyú és a turbina munkája legyen w_{SZ} és w_{T}, nagybetűs indexszel, hogy meg lehessen őket különböztetni a w_t általános technikai munka jeltől.
10) A 4.5-ös egyenletbe bele próbáltad írni gondolom magyarázatként az átalakított első főtételt, de zavaros lett, és amúgyis jobb lenne, ha egy külön magyarázó mondatban lenne.

Az adatlekéréshez kik ell találni tipukus értékeket, ehhez meg kell nézni, hogy azok mekkorák (p_K, p_L, T_H), de ha már utánanézel ezeknek, akkor le is lehet írni. Első körben a teljes izobár görbéket tudod lekérezni , amik túllógnak a körfolyamaton. Ezekből vagy Wolframban, vagy az ábrázolásnál le lehet vágni a felesleges végeket. Amikor kézzel rajzolod, akkor is először megrajzolod a fő vonalakat, aztán vastagon kiemeled a körfolyamat állapotváltozásait.

Az az "alap függvény" a két fázishatár, a cseppfolyós-nedves gőz (x=0) és a nedves gőz-légnemű (x=1) fázishatár. és az izobár vonal tényleg nem távolodik el a fázishatártól. Amikor kézzel a táblára rajzoltam, akkor szándékosan torzítottam el, hogy látszon valami különbség az 1-es és a 6-os pont között. Emiatt írtam 7. pontot.

**Comment by GroberAdel** [comment]
Tisztelt Tanár Úr!
A kisebb módosításokat megcsináltam, sajnos a T-s diagramot nem sikerült úgy, ahogy elvárt lett volna, illetve a mentés után valamiért nem futott le a fájlom, ezért újból klónoztam-mentettem-másoltam, végül sikerült a saját ágamra egy sikeresen lefuttatott verziót feltölteni.
Azt szeretném kérdezni, hogy jelenleg, ebben az állapotában hány pontot ér a beadandó? Mert láttam, hogy a neptun kódom mellett zöld a cella, de pontszám nem volt még odaírva. Vagy ahhoz először a mester ágra kell feltölteni?

**Comment by Szalay** [comment]
Technikailag rendben van a beadandó: sikerült feltölteni mindent, a fájlok a helyükön vannak, és le is fordul hiba nélkül

Tartalmi szempontból viszont nem ilyen jó a helyzet. 
1) Az állapotváltozásokról külön egy-egy mondatnyi leírás kellene.
2) Ez felsorolás jellegű, de technikailag ne felsorolás (enumeration vagy itemize) legyen, hanem folyó szöveg! A séma ilyesmi legyen:
```
\noindent $\pgfcircled{1b.} - \pgfcircled{2.}$: \textbf{Hőközlés állandó nyomáson} %az állapotváltozás fajtája

szerepe és a megvalósító berendezés,

a vonatkozó általános összefüggések és alkalmazásuk az adott állapotváltozásra,

és ezután jöhetnek még a szokásos vagy jellemző értékek, egyéb megjegyzések.
```
A T-s diagram nem csak nem szép, hanem hibás is.
1) Rajt hagytad a rácsot.
2) A q_{EL}-nek megfelelő terület rosszul lett megjelölve.
3) A területek inkább valamilyen színnel legyenek kitöltve, hogy egyértelműen látsszon a határuk!
4) A szivattyú munkájának megjelölésénél sikerült elégg eltúlozni az 1b. pont helyét. Ehelyett egy kisebb második T-s diagram kellene, amiben ezt a részt kiemeled. A többiektől, akiknek szivattyús feladatuk volt, ugyanezt kértem.
5) A fő T-s diagramhoz két adatsor kell, a két izobár vonal, a szokásosnak megfelelő nyomásértékekkel. A függőleges szakaszok lehetnek sima vonalak, ahogy most vannak. Ha az izobár vonalakat görbeként ábrázolod, akkor a terülekitöltés is egyszerű lesz.
6) Nyílfejet az állapotváltozások görbéinek közepére a `mid arrow=szín` tulajdonsággal lehet tenni.

Néhány további megjegyzést a forrás mellé írtam: https://github.com/PE-MK-JAKI-H/MHEK/commit/0ade018991708c91026e2da109808b8c241d5e77

**Comment by GroberAdel** [comment]
Tisztelt Tanár Úr!

A végleges verziót feltöltöttem az ágamra, amit tudtam, javítottam. A T-s diagramnál kitöröltem a rajzolt vonalakat, a wolframból kértem le adatokat az izobár vonalakhoz.

Tisztelettel,
Grőber Adél

**Comment by Szalay** [comment]
Átnéztem és pontoztam, az eredményt megtalálod a Google-táblázatban.
