### ISSUE TITLE
E7 végleges

### ISSUE THREAD

**Issue by szeiferta** [PE-MK-JAKI-H/MHEK#20]
Kedves Tanár úr!

Elkészültem a végleges verzióval.  Fel is töltöttem.

**Comment by Szalay** [comment]
Átnéztem és pontoztam a jelenlegi állapot alapján, az eredményt megtalálod a Google-táblázatban. Messze nem tökéletes, de az elfogadható szintet eléri.

Ha szeretnél javítani a beadandón, akkor írok egy listát a hibákról, de gondolom ez függ attól is, hogy a másik feladatod értékelése milyen lesz a javítás után.

**Comment by szeiferta** [comment]
Kedves Tanár úr!

Érdekelne,hogy az elméleti részben milyen hibák voltak.  Mindkettőnél megpróbálom a hibákat javítani.
Köszönöm!

**Comment by Szalay** [comment]
Megjelöltem a forrásban a javítandó dolgokat a következő helyeken:
https://github.com/PE-MK-JAKI-H/MHEK/commit/35c692d2e65fe6cacf39e383da973c10d973b6ea
https://github.com/PE-MK-JAKI-H/MHEK/commit/098fa0e9ec2d5d697aa077c014a5b4ea3cdb89a1

https://github.com/PE-MK-JAKI-H/MHFGY/commit/417e9302322c2f9bcee70082b9b409139078f851
https://github.com/PE-MK-JAKI-H/MHFGY/commit/417e9302322c2f9bcee70082b9b409139078f851

A lefordított PDF ne maradjon ki a feltöltésből!
