### ISSUE TITLE
Tiszta fojtás, ellenőrzés

### ISSUE THREAD

**Issue by Balint12** [PE-MK-JAKI-H/MHEK#21]
Tisztelt Tanár Úr!
Szeretném kérni a fojtásos (22.) elméleti feladatom ellenőrzését.
A T-s diagramot nem csináltam meg, eredetileg felvettem egy 75 pontos gyakorlati feladatot (már leadtam), és ezt az elméleti feladatot, a gyakorlati feladatom bővítette 100 pontra, de én ezt az elméleti feladatot nem adtam le.
Ha szükséges meg tudom csinálni a T-s diagramot is péntekig.

Tisztelettel:
Vörös Bálint

**Comment by Szalay** [comment]
Ez a feladat 100 pont fölött volt és nem is volt szükséged több pontra.
