### ISSUE TITLE
Feladat leadás

### ISSUE THREAD

**Issue by CsTD-PE** [PE-MK-JAKI-H/MHEK#22]
Tanár Úr!
Sikerült feltennem .tex kiterjesztésben mindent!
Legyen szíves ellennőrizni!

**Comment by Szalay** [comment]
Csak egy üres fájlt töltötél fel: https://github.com/PE-MK-JAKI-H/MHEK/tree/FDE7S8

**Comment by CsTD-PE** [comment]
Most legyen szíves megnézni a branchet

**Comment by Szalay** [comment]
Most sikerült feltölteni. Átnéztem és pontoztam a jelenlegi állapot alapján, az eredményt megtalálod a Google-táblázatban.

Ha szeretnél javítani a beadandón, akkor írok egy listát a hibákról. Nincs túl sok, az egyetlen komolyabb az, hogy nem úszik az úszófej.

**Comment by CsTD-PE** [comment]
Ha a 77 pont megvan legalább 2es, akkor nekem megfelel.
Azt hogy nem úszik az úszófej, így nekem balladai homály.
