### ISSUE TITLE
E17 és E26 feladatok

### ISSUE THREAD

**Issue by MDani0521** [PE-MK-JAKI-H/MHEK#23]
Tisztelt Tanár Úr!
Feltöltöttem a feladataimat.

**Comment by Szalay** [comment]
Átnéztem és pontoztam, az eredményt megtalálod a Google-táblázatban.

A pull requestet elutasítottam, nem is kellett volna kérni.

**Comment by MDani0521** [comment]
Rendben, köszönöm.
Ahhoz, hogy elfogadjam a jegyet van valami teendőm?

**Comment by Szalay** [comment]
Nincs már más teendőd.
