### ISSUE TITLE
MHEK_4/32_II8M0A

### ISSUE THREAD

**Issue by Szalay** [PE-MK-JAKI-H/MHEK#25]

**Comment by Szalay** [comment]
Megnéztem a beadandót, és van néhány javítandó probléma:
1) A T(A) diagramhoz kellene egy számítás, hogy ésszerű értékek legyenek ábrázolva.
2) Az úszófej mögött rajt hagytad a merev csőköteges hőcserélő jobboldali fejét.
3) A nyilak helyenként egymásra lógnak.

![image](https://user-images.githubusercontent.com/8204804/83164132-27f0e680-a10c-11ea-9737-e436b1c053bb.png)

Ezeket javítani kellene. A végső határidő jövő hétfő.

**Comment by HalasiDoki** [comment]
Tisztelt Szalay István!
Feltöltöttem, amire jutottam végül, azonban időhiány miatt ez sajnos nem sok.
Előre is köszönöm az ellenőrzést!

**Comment by Szalay** [comment]
Átnéztem és pontoztam, az eredményt megtalálod a Google-táblázatban.
