### ISSUE TITLE
MHEK 20.feladat

### ISSUE THREAD

**Issue by ABotondM** [PE-MK-JAKI-H/MHEK#3]
Tisztelt Tanár Úr! 
Azt szeretném megkérdezni, hogy a mellékelt képen látható kapcsolási vázlatot és diagramot elkezdhetem-e programozni, vagy valamiben esetleg hiányos? 
![hőtankép](https://user-images.githubusercontent.com/63011265/79757260-
![hőtankép](https://user-images.githubusercontent.com/63011265/79757289-303f5000-831c-11ea-9b9f-03a3fa66bdbf.jpg)

**Comment by Szalay** [comment]
A kapcsolási rajz is és a T-s diagram is rendben vannak. A kapcosléási rajzon elég lesz a betűjeleket feltüntetni. A T-s diagramhoz találsz mintát a Moodle-ben. Ha nem sikerült adatot előállítani hozzá, akkor jelezd.
