### ISSUE TITLE
Feltöltött munka

### ISSUE THREAD

**Issue by rupiman97** [PE-MK-JAKI-H/MHEK#4]
Jó napot tanár úr!
Legyen szíves megnézni az elméleti feladatomat, hogy mit javítsak benne, vagy írjak hozzá.
Illetve a hőkörfolyamatoknál nem szerepel pontszám az excel táblában, azt meglehet kérdezni, hogy előreláthatólag hány pontot fog érni?

**Comment by Szalay** [comment]
Megnéztem ezt a feladatot is, de ez nincs olyan jó szinten, mint a másik. Szerencse, hogy végülis nincs rá szükség.
