### ISSUE TITLE
MHEK 20.feladat ellenőrzés

### ISSUE THREAD

**Issue by ABotondM** [PE-MK-JAKI-H/MHEK#5]
Tisztelt Tanár Úr ! 
Azt szeretném kérdezni Öntől, hogy tudna-e mondani egy becslést, hogy a fent említett feladatra a jelenlegi állapotában hány pontot lehetne kapni? Azért lenne ez fontos, mert még akár éppen benne is lehetne a +10% os határidőben, amennyiben a megoldás eléri az elégséges szintet.
Válaszát előre is köszönöm!

**Comment by Szalay** [comment]
Átnéztem a megoldást. Komoly hiba nincs benne, de hiányosság annál több, mert a feladatnak csak egy részét oldottad meg.

A következőket kell javítani:
1) A tömegfajlagos munka jele kis w, nem omega.
2) A q_K helyett az ábrán q_{Elvont} van, az egyenleteknél egyik sem jelenik meg. Legyen mindenhol q_K!
3) A rács jó, hogy az ábrán van, ha segít szerkeszteni, de ne maradjon rajt a végleges változatban! A vágómaszk viszont, hamár úgyis ott van a forrásban, legyen engedélyezve!
4) Az állapotváltozások irányát jelölni kellene, a legegyszerűbb módja a `mid arrow=blue` tulajdonság beállítása.
5) Az ábra nem egyszerűen egy víz-gőz T-s diagram, hanem a Rankine--Clausius-körfolymat ábrája víz-gőz T-s diagramban.
6) A feladat címe "A túlhevítést alkalmazó Rankine--Clausius-körfolyamat" legyen!
7) Az egyenleteknél az indexelést javítnai kell.
8) Nem hiba, inkább csak javaslat, hogy a kitöltések vonalkázás helyett valamilyen halvány színnel történjenek.

A kapcsolási vázlat elvi felépítése jó, a jelölések nem mindenhol logikusak és szabályosak: 
1) az 1-es legyen sarkon, mint a 4-es, 
2) a 2-es pont van a kazánban, és a K betűjel legyen kívül, 
3) a 3-as pontot meg lehet jelölni,
4) nyilat tenn ielegendő az első és a felső vízszintes szakaszokra, és itt is a mid arrow alkalmazható
5) A generátor mellet a háom vonal legyen 45°-os, kb. 2/3-d hosszú és kicist közelebb egymáshoz. Ez szabványos jelölés.
6) A T is inkább a turbina jelén kívül legyen.

A következőket kellene még megcsinálni:
1) Kifejteni az egyes szakaszokhoz tartozó állapotváltozásokat, és ezekhez kapcsolódóan írni fel a feladat szövegében megadott mennyiségeket. Így logikus lesz enne ka résznek a felépítése, és könnyebb megmagyarázin, hogy pl. az 1-4 szakssz izobár, és állandó nyomás esetén az első főtétel adott alakja érvényes, és ebből következik a q_{1-4} számítása módja.

A fentiek javításával hármas-négyes szintre és elfogadható állapotba kerül a beadandó. Ha esetleg ennél jobbat szeretnél, akkor a T-s diagramot lehet bővíteni hőmérséklet és fajlagos entrópia értékek megjelölésével és hőtartalom vonalak felrajzolásával.

A +10 % pedig nem +10 %, hanem 1,1-es szorzó, azaz mondjuk 40 %-ról 44 %-ra visz.

**Comment by ABotondM** [comment]
Köszönöm, javítottam. Kérem a Tanár Úrat nézze át ismét!

**Comment by Szalay** [comment]
Átnéztem újra, hibák számát sikerült jelentősen csökkentened, úgyhogy le is pontoztam, viszont azt látni fogod, hogy az ábrák ugyan felfelé húzták az értékelést, de a magyarázatok kidolgozottsága még mindig nem túl jó (=részletes), illetve apróbb hibák is maradtak még.

A Google-táblázatban megtalálod az értékelést, ami a következő apróbb hibák javítása után érvényes:
1) Amiket megjelöltem a forrásban itt: https://github.com/PE-MK-JAKI-H/MHEK/commit/8d988d703569c29d54f87f82a0727209e037944f
2) A T-s diagramon az 1-2 és a 3-4-5 szakaszon a kék görbe fölött van egy vékony fekete vonal is.
3) A legutolsó sort leszámítva a zárójelezés fölösleges, és pontosvessző helyett vesszőt hasznájl!
4) Először az írod, hogy az 1-2 szakasz adiabatikus hőközlés (=hőközlés nélküli hőközlés), aztán a végén azt, hogy az 1-4 szakasz izobár.
5) A hő nem tud megváltozni. Ha entalpia helyett hőtartalmat írsz, akkor magad is rájössz, hogy a "hőtartalom-változás megegyezik a hő megváltozásával" valahogy sántít.
6) Eltérő módon jelölöd a pontokat a két diagramban, mindegyik jó, csak legyen egyforma.

A nagyobb javítást igénylő hiányossságok:
1) A megoldásnak ki kellene találni egy logikus felépítést, ami ennél a feladatnál nem is olyan bonyolult: a T-s diagram lehet az első, a kapcsolási vázlat a második, és az állapotváltozások leírási és a hozzájuk tartozó jellemzők és számítási összefüggések a harmadik rész.
2) Ezt a harmadik részt részletesen ki kellene fejteni: a szakaszok és a részeik fajtái, az összefüggések indoklással (pl. hogyan jön az első főtételből), a kapcsolódó állapotjelzők és folyamatjelzők nevei, jelentésük, mértékegységeik, a körfolyamathoz tartozó nevezetes nyomás és hőmérséklet értékek feltüntetése.
3) Az előző pont mennyiségeinek megjelölése a T-s diagramban.

Ui.: Urat. Olyanokat sem mondasz, hogy kézet meg nyárat.

**Comment by Szalay** [comment]
A kibővített leírás nem igazán a körfolyamathoz tartozik, és hibák is vannak benne. A kisbetűs mennyiségek lehetnének ugya a moláris megfelelőik jelei, de a mértékegységük szerint nem azok. És a mértékegységük jó, nem a nevük.

Felírtál olyan összefüggéseket is, amik csak ideális gázra érvényesek, de a vízgőz nem az.

Ezektől függetlenül kicsit javít a megoldáson a kiegészítés, úgyhogy módosítottam a pontozást.
A +5 %-ot meghagytam, mert még a határidő előtt érkezett be a megoldás.
