### ISSUE TITLE
MHEK 6/24

### ISSUE THREAD

**Issue by hevesitamas** [PE-MK-JAKI-H/MHEK#6]
Tisztelt Tanár Úr!
Lenne szíves ellenőrizni a feladatom és meg tudná mondani mit kell még rajta javítanom, hogy legalább a kettes szintet elérje?
Előre is köszönöm!

**Comment by Szalay** [comment]
A legnagyobb gond, hogy nem tudod felmérni, hogy milyen szinten van a beadandód. A pontoztam a jelenlegi állapot alapján. Komoly hibát nem látok, de apróbb javítanivaló lenne bőven. Ha ezeket szeretnéd kijavítani, akkor írok egy listát.

**Comment by hevesitamas** [comment]
Tisztelt Tanár Úr!
Köszönöm a gyors választ. A jelenlegi pontozás nekem megfelel nem szeretnék már javítani rajta.
