### ISSUE TITLE
P9HNUA újra ellenőrizhető

### ISSUE THREAD

**Issue by molnzsofi** [PE-MK-JAKI-H/MHEK#8]
Tisztelt Tanár úr!

A javítások elkészültek, a feladatot újra ellenőrizheti.

Köszönettel,
Molnár Zsófia és Hegedűs Anett

**Comment by Szalay** [comment]
Átnéztem és pontoztam, az eredményt megtaláljátok a Google-táblázatban. Két emberre kicsit kevés, amit elkészítettetek, ha bővítenétek, akkor még jövő hétfőig van erre lehetőségetek

**Comment by molnzsofi** [comment]
Ezzel az eredménnyel megvan az elégséges érdmjegyünk? Ha igen akkor szeretnénk így elfogadni.

**Comment by Szalay** [comment]
50 %-tól jár kettes, így a fejenkénti 53,6 %-kal megvan a kettes mindkettőtöknek. Megjelölöm, hogy elfogadtátok.
