### ISSUE TITLE
MHEK 3/16 és 5/23 ellenőrzés

### ISSUE THREAD

**Issue by KocsisBence2398** [PE-MK-JAKI-H/MHEK#9]
Tisztelt Tanár úr!

Kérem ellenőrizze le a feladatokra készített megoldásaim.

Az 5/23-as feladat termodinamikai hatásfokra vonatkozó utolső kérdését Hadabás Márk (TV3AA4) segített elkészíteni, ezért az arra járó pontokat neki ajánlom fel.

Válaszát előre köszönöm!

Tisztelettel,
Kocsis Ferenc Bence
I2KLVY

**Comment by Szalay** [comment]
Hát, előszöris meg kell rójjalak, amiért elfoglaltál két 100 pontos feladatot. Másodszor pedig a Hadabás úr nem kap pontot, mert nem szólt, hogy elég egy ötöst szerezni.

A rácsot a T-s diagramokról levehetted volna, illetve igazodhattál volna az eredeti feladatszámozáshoz. Ha az időd engedi, a félév végéig biztosan elérhető marad a GitHub tároló és esetleg kiigazíthatod ezeket.

Idő hiányában a második feladatodat nem is pontoztam, de ránézésre az is 80 % felett lett volna.
